### ISSUE TITLE
Error when changing resolution

### ISSUE THREAD

**Issue by EECJC17** [wrfchem-leeds/WRFotron#45] opened 2021-10-05 12:56 UTC
Hi

I'm trying to get a run working with a Western European domain and a 50km resolution. Whenever I try to run it, I get no output files. The bottom of the rsl.error.0000 file gives me this:
![image](https://user-images.githubusercontent.com/75302097/136024372-856ff2f0-d046-49b4-b0b7-27724233158d.png)

I'm not entirely sure what I am doing wrong here. I have changed the timesteps proportionally in namelist.chem.blueprint up to 5.0, 50 and 5.0 respectively and changed the meteorological timestep to 300 as this is also an increase of 2/3 over the default number. I have also run this with the default 180 meteorological timestep and got the same error. The commas in the namelists all seem to be where they should be, so I don't think it's a typo. I have changed the resolution for other simulations before, using the same method and not had this issue.

The pre-processors all worked, so I don't believe the issue is there. I also have a simulation which is running the same domain, except at the default 30km resolution and timesteps, which is working fine. The error message itself doesn't seem to be mentioning anything to do with resolution, but it's only changing the resolution and timesteps that seem to be causing it to appear.

Do you know what this error means and how I should go about fixing it?

Thank you

**Comment by lukeconibear** [comment] 2021-10-05 13:40
Hi Connor,

You've compiled your own WRFChem in `/nobackup/eecjc/WRFChem4.2_RCP8_5`. This would be fine, however, this is not actually version 4.2. Instead, you've downloaded and compiled the latest release, which is version 4.3. You can check this by looking at the top of the `README`. In version 4.3, some new urban physics were added (see [release note](https://github.com/wrf-model/WRF/releases/tag/v4.3)). This added some new parameters to `URBPARM.TBL`, which you can see [here](https://github.com/wrf-model/WRF/blob/master/run/URBPARM.TBL#L470-L508). `GR_FLAG` is one of these new parameters. As WRFMeteo4.2 (CEMAC module) doesn't have these parameters, it will break in the error you shared above.

Overall, the cause of this error is the version mismatch between WRFChem**4.3** (your own copy) and WPS**4.2** / WRFMeteo**4.2** (CEMAC modules). They all need to be the same version. 

The solution is to download and compile WRFChem4.2, or instead to make your own versions of WPS4.3 and WRFMeteo4.3. Seeing as you've already gone through the steps to create your own WRFChem, it may be easier to just change this. You can download a specific release of a GitHub repository using the `--branch` flag. So, to download WRFChem4.2 you can use:
```bash
git clone https://github.com/wrf-model/WRF.git --branch v4.2 WRFChem4.2_RCP8_5
```
Compile this, update `config.bash`, and the problem should be fixed.

**Comment by EECJC17** [comment] 2021-10-05 14:05
Hi Luke

Ah, that would explain things, I wasn't actually trying to use my own WRF-Chem for this one. I must have just completely missed that I hadn't switched it back to point at the CEMAC version.

Cheers for the tips about setting up new versions. That could explain why I have been having separate issues with ClWRF. I'll give that compilation a go and try that for my ClWRF tests.

**Closed** 2021-10-05 14:05 UTC
