### ISSUE TITLE
Run not producing output files

### ISSUE THREAD

**Issue by EECJC17** [wrfchem-leeds/WRFotron#40] opened 2021-04-29 09:21 UTC
Hi - just a minor issue and the problem is probably between the computer and the chair, but I could do with some help getting past it please:

I have been trying out a test run for a run that I switched domain to cover the Nile Delta and date to start from 01/01/2016 (I had not tried the 2nd step before, so I think I might be getting something wrong there). I changed the background surface temperature and pressure levels to what I think are the appropriate files, with December 2015 included to account for a 6 hour spinup time. The files I am pointing to are here:

![image](https://user-images.githubusercontent.com/75302097/116527508-a5037d80-a8d2-11eb-935c-5752250b7ce9.png)

Whenever I try to run this, the output folder produced only contains pp_concat_regrid.py and .bash. I get the following pre.bash.e* error:

![image](https://user-images.githubusercontent.com/75302097/116527606-c5333c80-a8d2-11eb-9697-306cecc388d7.png)

I'm aware the first bit of the error can often come from not requesting enough memory, but I don't think that's the case here as I requested 4gb for main.bash and it's a 24 hour test run.

I don't think the problem is in pre.bash, because when I try grep -i 'success' *.out *.log, I get the following: 
![image](https://user-images.githubusercontent.com/75302097/116528123-5a363580-a8d3-11eb-86e9-f19c925b5060.png).

The rsl.error files are within the chem_out folder, which I believe usually means it hasn't broken mid run? main.bash.e* mostly looks fairly normal, but has a bit in it that looks like this:

![image](https://user-images.githubusercontent.com/75302097/116528812-27d90800-a8d4-11eb-81ad-39efb88179fb.png)

post.bash.e* is completely blank.

If you need me to send through any other info, let me know

Thank you

Connor

**Comment by lukeconibear** [comment] 2021-04-29 12:13
Starting a simulation that begins in December can cause issues with `anthro_emis`. Was `anthro_emis` successful here?

If `anthro_emis` did fail, then try running a short test that begins in either November or January, and let me know the outcome.

**Comment by EECJC17** [comment] 2021-04-29 15:45
Cheers Luke!

I didn't know about the December thing - I've just completed another test run using mid Jan as the date and it is successfully completing the anthro emissions now - that showed up after the grep command. Unfortunately, it doesn't seem to have got rid of the entire problem. I'm still getting the first half of the pre.bash error:

![image](https://user-images.githubusercontent.com/75302097/116578968-d64b7000-a909-11eb-850d-b2a668a7e3c0.png)
From previous conversations with Ailish, this might be a timestep error? based on the rsl.error files going into the chem_out folder. If so, it's not something I know how to fix. 

I've also got a new bit to the main.bash.e*:

![image](https://user-images.githubusercontent.com/75302097/116579233-1a3e7500-a90a-11eb-8943-96b12ddb6bfe.png)

**Comment by lukeconibear** [comment] 2021-04-29 15:58
Those messages in `pre.bash.e*` are okay.

The memory issue in `main.bash.e*` is a problem. To find the cause of the issue, look at the bottom of the `chem_out/rsl.error.0000` file. This is unlikely to be the HPC requirements in `main.bash` and is more likely to be a timestep issue. When you changed your domain, did you also change the spatial resolution? If so, then you will also have to change the timesteps by the same fraction as these all work together (e.g., if you half the spatial resolution, then you half the timesteps).

Note, this will be for **all** timesteps (i.e., `time_step`, `chemdt`, and `bioemdt`), and not just the meteorological one.

**Comment by EECJC17** [comment] 2021-04-29 16:09
Ah, that'll be it. I did change the resolution from 30km to 10km - I wasn't aware you needed to change the timestep too for that. I have looked at the bottom of the chem_out file and that is suggesting that is the problem.

So I should change the timestep in namelist.wrf and the three (chemdt, bioemdt and photdt) in namelit.chem, is that correct?

**Comment by lukeconibear** [comment] 2021-04-29 16:14
Cool. Yes, divide them all by 3, and they should match up.

For models like WRFChem, the resolution and timestep are tied together (via the [CFL criterion](https://en.wikipedia.org/wiki/Courant%E2%80%93Friedrichs%E2%80%93Lewy_condition)), so if you change one you have to change the other.

**Comment by EECJC17** [comment] 2021-04-29 16:17
Brilliant, much appreciated. Thanks Luke!

**Comment by lukeconibear** [comment] 2021-04-29 16:22
Let me know if this solves the problem and then I'll close this issue.

**Comment by EECJC17** [comment] 2021-04-30 07:56
That appears to have dealt with the issue, thank you

**Comment by lukeconibear** [comment] 2021-04-30 08:06
Great, thanks for letting me know.

**Closed by lukeconibear** 2021-04-30 08:06 UTC
